"""Data structures for representing Lucide icon elements and metadata."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/core.ipynb.

# %% auto #0
__all__ = ['SvgElement', 'PathElement', 'CircleElement', 'RectElement', 'LineElement', 'EllipseElement', 'PolylineElement',
           'PolygonElement', 'IconData']

# %% ../nbs/core.ipynb #475b04fb
from dataclasses import dataclass, field
from typing import List, Dict, Optional, Union

# %% ../nbs/core.ipynb #afd45628
@dataclass
class PathElement:
    """SVG path element data."""
    d: str  # path data string

# %% ../nbs/core.ipynb #313e8821
@dataclass
class CircleElement:
    """SVG circle element data."""
    cx: str  # center x coordinate
    cy: str  # center y coordinate
    r: str   # radius

# %% ../nbs/core.ipynb #62d4cf02
@dataclass
class RectElement:
    """SVG rect element data."""
    x: str              # x position
    y: str              # y position
    width: str          # width
    height: str         # height
    rx: Optional[str] = None  # corner radius (optional)

# %% ../nbs/core.ipynb #dda40fc8
@dataclass
class LineElement:
    """SVG line element data."""
    x1: str  # start x
    y1: str  # start y
    x2: str  # end x
    y2: str  # end y

# %% ../nbs/core.ipynb #4edc988f
@dataclass
class EllipseElement:
    """SVG ellipse element data."""
    cx: str  # center x coordinate
    cy: str  # center y coordinate
    rx: str  # x radius
    ry: str  # y radius

# %% ../nbs/core.ipynb #dbb98380
@dataclass
class PolylineElement:
    """SVG polyline element data."""
    points: str  # space-separated coordinate pairs

# %% ../nbs/core.ipynb #785c489c
@dataclass
class PolygonElement:
    """SVG polygon element data."""
    points: str  # space-separated coordinate pairs

# %% ../nbs/core.ipynb #bf8849c4
# Union type for all SVG elements
SvgElement = Union[
    PathElement,
    CircleElement,
    RectElement,
    LineElement,
    EllipseElement,
    PolylineElement,
    PolygonElement
]

# %% ../nbs/core.ipynb #bb27fba0
@dataclass
class IconData:
    """Container for a Lucide icon's SVG elements and metadata."""
    elements: List[SvgElement]          # SVG child elements
    categories: List[str] = field(default_factory=list)  # category assignments
    tags: List[str] = field(default_factory=list)        # searchable tags
