"""SVG factory function for building FastHTML Lucide icon components."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/factory.ipynb.

# %% auto #0
__all__ = ['lucide_icon']

# %% ../nbs/factory.ipynb #e50aa278
from fasthtml.common import Svg
from fasthtml.svg import Path, Circle, Rect, Line, Ellipse, Polyline, Polygon

from cjm_fasthtml_lucide_icons.core import (
    IconData,
    SvgElement,
    PathElement,
    CircleElement,
    RectElement,
    LineElement,
    EllipseElement,
    PolylineElement,
    PolygonElement,
)

# %% ../nbs/factory.ipynb #8a476606
def _build_element(
    element: SvgElement  # element dataclass to convert
):  # FastHTML SVG element component
    """Convert an element dataclass to a FastHTML SVG component."""
    if isinstance(element, PathElement):
        return Path(d=element.d)
    elif isinstance(element, CircleElement):
        return Circle(cx=element.cx, cy=element.cy, r=element.r)
    elif isinstance(element, RectElement):
        attrs = {'x': element.x, 'y': element.y, 'width': element.width, 'height': element.height}
        if element.rx is not None:
            attrs['rx'] = element.rx
        return Rect(**attrs)
    elif isinstance(element, LineElement):
        return Line(x1=element.x1, y1=element.y1, x2=element.x2, y2=element.y2)
    elif isinstance(element, EllipseElement):
        return Ellipse(cx=element.cx, cy=element.cy, rx=element.rx, ry=element.ry)
    elif isinstance(element, PolylineElement):
        return Polyline(points=element.points)
    elif isinstance(element, PolygonElement):
        return Polygon(points=element.points)
    else:
        raise ValueError(f"Unknown element type: {type(element)}")

# %% ../nbs/factory.ipynb #561fe6ff
def _build_svg(
    icon_data: IconData,  # icon data containing SVG elements
    size: int = 5,        # Tailwind size scale (default 5 = 20px)
    cls: str = None,      # additional CSS classes
    **kwargs              # additional SVG attributes
) -> Svg:  # FastHTML Svg component
    """Build a FastHTML Svg component from IconData."""
    # Build child elements
    children = [_build_element(el) for el in icon_data.elements]
    
    # Build class string
    size_cls = f"w-{size} h-{size}"
    full_cls = f"{size_cls} {cls}" if cls else size_cls
    
    # Standard Lucide SVG attributes
    svg_attrs = {
        'xmlns': 'http://www.w3.org/2000/svg',
        'viewBox': '0 0 24 24',
        'fill': 'none',
        'stroke': 'currentColor',
        'stroke_width': '2',
        'stroke_linecap': 'round',
        'stroke_linejoin': 'round',
        'cls': full_cls,
        **kwargs
    }
    
    return Svg(*children, **svg_attrs)

# %% ../nbs/factory.ipynb #f601ac02
def lucide_icon(
    name: str,        # icon name (e.g., "folder", "arrow-up")
    size: int = 5,    # Tailwind size scale (default 5 = 20px)
    cls: str = None,  # additional CSS classes (e.g., daisyUI colors)
    **kwargs          # additional SVG attributes
) -> Svg:  # FastHTML Svg component
    """Get a Lucide icon as a FastHTML Svg component."""
    # Import here to avoid circular dependency
    from cjm_fasthtml_lucide_icons.registry.icons import ICONS
    
    icon_data = ICONS.get(name)
    if icon_data is None:
        available = ', '.join(sorted(list(ICONS.keys())[:10])) + ', ...'
        raise ValueError(f"Unknown icon: '{name}'. Available icons include: {available}")
    
    return _build_svg(icon_data, size=size, cls=cls, **kwargs)
